AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AvailabilityZone:
    Type: String
    Default: us-east-1a

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Sub ${AvailabilityZone}

  MyEBS:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Sub ${AvailabilityZone}
