AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyEBS:
    Type: AWS::EC2::Volume
    Properties:
      AutoEnableIO: false
      AvailabilityZone: us-east-1a
      Encrypted: false
      Iops: 3000
      MultiAttachEnabled: false
      Size: 4
      Tags:
        - Key: Name
          Value: MyEBS
      Throughput: 4
      VolumeType: gp3
