AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: my-iam-user
      Tags:
        - Key: one
          Value: !Sub ${AWS::Region}-one # us-east-1-one
