AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: my-iam-user
      Tags:
        - Key: one
          Value: !Select [0, !Split [ ",", "one,two,three" ]] # one
