AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: my-iam-user
      Tags:
        - Key: one
          Value: !Ref MyIAMGroup # my-cf-1-MyIAMGroup-1OU9QBHYFRQG
  
  MyIAMGroup:
    Type: AWS::IAM::Group
