AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones: [us-east-1a, us-east-1b]
      Listeners:
      - InstancePort: 80
        LoadBalancerPort: 80
        Protocol: HTTP
